---

- name: prom2teams | Ensure prom2teams directories structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"
    mode: "0755"
  with_items:
    - "{{ prom2teams_config_folder }}"
    - "{{ prom2teams_logs_folder }}"

- name: prom2teams | Copy prom2teams ini configuration
  ansible.builtin.template:
    src: "{{ prom2teams_ini_template_path }}"
    dest: "{{ prom2teams_config_folder }}/prom2teams.ini"
    mode: "0640"
    owner: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"
  notify: restart prom2teams

- name: prom2teams | Copy prom2teams env configuration
  ansible.builtin.template:
    src: "{{ prom2teams_config_environment_template_path }}"
    dest: "{{ prom2teams_config_folder }}/prom2teams"
    mode: "0640"
    owner: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"
  notify: restart prom2teams

- name: prom2teams | Copy prom2teams uwsgi configuration
  ansible.builtin.template:
    src: "{{ prom2teams_config_uwsgi_template_path }}"
    dest: "{{ prom2teams_config_folder }}/uwsgi.ini"
    mode: "0640"
    owner: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"
  notify: restart prom2teams

- name: prom2teams | Copy wsgi.py app runnable
  ansible.builtin.copy:
    src: "{{ prom2teams_wsgi_app_file_path }}"
    dest: "{{ prom2teams_uwsgi_runnable_path }}"
    mode: "0644"
    owner: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"

- name: prom2teams | Copy logrotate config
  ansible.builtin.template:
    src: "{{ prom2teams_logrotate_template_path }}"
    dest: /etc/logrotate.d/prom2teams
    mode: "0644"
    owner: root
    group: root
  when: prom2teams_logrotate_enabled
