---
- name: prom2teams | Ensure prom2teams group
  ansible.builtin.group:
    name: "{{ prom2teams_group }}"

- name: prom2teams | Ensure prom2teams user
  ansible.builtin.user:
    name: "{{ prom2teams_user }}"
    group: "{{ prom2teams_group }}"
    shell: /bin/bash

- name: prom2teams | Installing dependencies
  ansible.builtin.yum:
    name: "{{ prom2teams_required_libs_el7 }}"
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

- name: prom2teams | Installing dependencies
  ansible.builtin.yum:
    name: "{{ prom2teams_required_libs_el8 }}"
  when: (ansible_facts['distribution'] == "AlmaLinux" and ansible_facts['distribution_major_version'] == "8")

- name: prom2teams | Installing required pip packages
  ansible.builtin.pip:
    name: "{{ prom2teams_required_pip_packages }}"
    executable: pip3
  notify: restart prom2teams

- name: prom2teams | Installing prom2teams
  ansible.builtin.pip:
    name: prom2teams
    version: "{{ prom2teams_version }}"
    executable: pip3
  notify: restart prom2teams

- name: prom2teams | Copy Daemon script
  ansible.builtin.template:
    src: "{{ prom2teams_service_template_path }}"
    dest: /etc/systemd/system/prom2teams.service
    mode: 0644
  notify: restart prom2teams
