---
- name: Converge
  hosts: all
  vars:
    prometheus_msteams_version: 1.5.2
    prom2teams_webhook_urls:
      Connector: https://test.com

  tasks:
    - name: "Include rezizter.ansible-prom2teams"
      include_role:
        name: "rezizter.ansible-prom2teams"
