---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    prometheus_msteams_version: 1.5.2
    prom2teams_webhook_urls:
      Connector: https://test.com

  tasks:
    - name: "Include rezizter.ansible_prom2teams"
      ansible.builtin.include_role:
        name: "rezizter.ansible_prom2teams"
