---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    #image: geerlingguy/docker-centos8-ansible:latest
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
